# Generated by Django 5.2.4 on 2025-08-26 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 country code (e.g., 'US', 'GB', 'IN')", max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text="International phone number (e.g., '+1234567890')", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format (e.g., +1234567890)', regex='^\\+[1-9]\\d{1,14}$')]),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users_user',
        ),
    ]
