# Generated by Django 5.2.4 on 2026-01-10 00:22

from django.db import migrations
from django.db.models import Count

def remove_duplicate_emails(apps, schema_editor):
    """Remove duplicate emails - keep the oldest user, delete/update others"""
    User = apps.get_model('users', 'User')
    
    # Find duplicate emails
    duplicates = User.objects.values('email').annotate(
        count=Count('email')
    ).filter(count__gt=1)
    
    for dup in duplicates:
        email = dup['email']
        # Get all users with this email, ordered by date_joined (keep oldest)
        users = User.objects.filter(email=email).order_by('date_joined')
        
        # Keep the first one, update others
        keep_user = users.first()
        for user in users[1:]:
            # Update email to make it unique (add user ID)
            user.email = f"{user.id}_{email}"
            user.save()
            print(f"Updated duplicate email for user {user.id}: {email} -> {user.email}")

def reverse_remove_duplicate_emails(apps, schema_editor):
    """Reverse migration - restore original emails"""
    # This is a one-way migration, can't easily reverse
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_user_type'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_emails, reverse_remove_duplicate_emails),
    ]
