# Generated by Django 5.2.4 on 2026-01-16 18:01

from django.db import migrations


def populate_full_name_and_required_fields(apps, schema_editor):
    """Populate full_name from existing name, first_name+last_name, or email"""
    User = apps.get_model('users', 'User')
    
    for user in User.objects.all():
        # Populate full_name from existing fields
        if not user.full_name or user.full_name == 'User':
            if user.name:
                user.full_name = user.name
            elif user.first_name or user.last_name:
                full_name = f"{user.first_name or ''} {user.last_name or ''}".strip()
                if full_name:
                    user.full_name = full_name
                else:
                    user.full_name = user.email.split('@')[0]  # Use email username as fallback
            else:
                user.full_name = user.email.split('@')[0]  # Use email username as fallback
        
        # Ensure phone and country_code have values (they have defaults but let's be explicit)
        if not user.phone or user.phone == '+10000000000':
            # Keep existing phone if valid, otherwise use default
            pass  # Default is already set
        
        if not user.country_code or user.country_code == 'US':
            # Keep existing country_code if valid, otherwise use default
            pass  # Default is already set
        
        user.save()


def reverse_populate(apps, schema_editor):
    """Reverse migration - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_full_name_alter_user_country_code_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_full_name_and_required_fields, reverse_populate),
    ]
