# Generated by Django 5.2.4 on 2026-01-16 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_populate_full_name_and_required_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(help_text="ISO 3166-1 alpha-2 country code (e.g., 'US', 'GB', 'IN')", max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(help_text="User's full name", max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text="International phone number (e.g., '+1234567890')", max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format (e.g., +1234567890)', regex='^\\+[1-9]\\d{1,14}$')]),
        ),
    ]
