# Generated by Django 5.2.4 on 2025-10-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADBUQCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('billboard_count', models.IntegerField(default=0)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ADBUQ City',
                'verbose_name_plural': 'ADBUQ Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ADBUQMediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('billboard_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ADBUQ Media Type',
                'verbose_name_plural': 'ADBUQ Media Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ADBUQScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_pages_scraped', models.IntegerField(default=0)),
                ('total_billboards_found', models.IntegerField(default=0)),
                ('total_billboards_saved', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('cities_scraped', models.JSONField(blank=True, default=list)),
                ('media_types_scraped', models.JSONField(blank=True, default=list)),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('memory_usage_mb', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ADBUQ Scraping Log',
                'verbose_name_plural': 'ADBUQ Scraping Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ADBUQBillboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('display_height', models.CharField(blank=True, max_length=20, null=True)),
                ('display_width', models.CharField(blank=True, max_length=20, null=True)),
                ('ooh_media_type', models.CharField(db_index=True, max_length=100)),
                ('ooh_media_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('billboard_type', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('price_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('availability_date', models.CharField(blank=True, max_length=100, null=True)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('videos', models.JSONField(blank=True, default=list)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('traffic_flow', models.TextField(blank=True, null=True)),
                ('exposure_time', models.CharField(blank=True, max_length=100, null=True)),
                ('average_daily_views', models.CharField(blank=True, max_length=20, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('data_quality_score', models.IntegerField(default=0, help_text='Score from 0-100 based on data completeness')),
                ('needs_review', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ADBUQ Billboard',
                'verbose_name_plural': 'ADBUQ Billboards',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['city', 'is_active'], name='adbuq_adbuq_city_0f130e_idx'), models.Index(fields=['ooh_media_type', 'is_active'], name='adbuq_adbuq_ooh_med_823bbd_idx'), models.Index(fields=['price_numeric', 'is_active'], name='adbuq_adbuq_price_n_0835b0_idx'), models.Index(fields=['is_available', 'is_active'], name='adbuq_adbuq_is_avai_7058d3_idx'), models.Index(fields=['scraped_at'], name='adbuq_adbuq_scraped_a4aa36_idx')],
            },
        ),
    ]
