# Generated by Django 5.2.4 on 2025-10-25 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('recipient_type', models.CharField(choices=[('all_users', 'All Users'), ('billboard_owners', 'Billboard Owners Only'), ('advertisers', 'Advertisers Only'), ('specific_users', 'Specific Users')], default='all_users', max_length=20)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_panel_notification_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotificationCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('recipient_type', models.CharField(choices=[('all_users', 'All Users'), ('billboard_owners', 'Billboard Owners Only'), ('advertisers', 'Advertisers Only'), ('specific_users', 'Specific Users')], default='all_users', max_length=20)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('opened_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_panel_notification_campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotificationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sent', models.IntegerField(default=0)),
                ('total_delivered', models.IntegerField(default=0)),
                ('total_opened', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('android_sent', models.IntegerField(default=0)),
                ('ios_sent', models.IntegerField(default=0)),
                ('web_sent', models.IntegerField(default=0)),
                ('delivery_rate', models.FloatField(default=0.0)),
                ('open_rate', models.FloatField(default=0.0)),
                ('failure_rate', models.FloatField(default=0.0)),
                ('avg_delivery_time', models.FloatField(default=0.0)),
                ('peak_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='admin_panel.adminnotificationcampaign')),
            ],
            options={
                'db_table': 'admin_panel_notification_analytics',
            },
        ),
        migrations.CreateModel(
            name='AdminNotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, max_length=10, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='admin_panel.adminnotificationcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notification_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_panel_notification_recipient',
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'user')},
            },
        ),
    ]
