# Generated by Django 5.2.4 on 2026-04-12 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adminnotificationcampaign',
            index=models.Index(fields=['status', 'created_at'], name='admin_panel_status_9fd214_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotificationcampaign',
            index=models.Index(fields=['recipient_type', 'status'], name='admin_panel_recipie_66369c_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotificationrecipient',
            index=models.Index(fields=['campaign', 'status'], name='admin_panel_campaig_7f3135_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotificationrecipient',
            index=models.Index(fields=['user', 'status'], name='admin_panel_user_id_9cab17_idx'),
        ),
    ]
