# Generated by Django 5.2.4 on 2025-07-23 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_boards', models.CharField(blank=True, max_length=10, null=True)),
                ('average_daily_views', models.CharField(blank=True, max_length=20, null=True)),
                ('traffic_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('road_position', models.CharField(blank=True, max_length=100, null=True)),
                ('road_name', models.CharField(blank=True, max_length=100, null=True)),
                ('exposure_time', models.CharField(blank=True, max_length=100, null=True)),
                ('price_range', models.CharField(blank=True, max_length=100, null=True)),
                ('display_height', models.CharField(blank=True, max_length=20, null=True)),
                ('display_width', models.CharField(blank=True, max_length=20, null=True)),
                ('advertiser_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('advertiser_whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('ooh_media_type', models.CharField(max_length=100)),
                ('ooh_media_id', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=50)),
                ('images', models.JSONField(blank=True, default=list)),
                ('unavailable_dates', models.JSONField(blank=True, default=list)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billboards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
