# Generated by Django 5.2.4 on 2025-07-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='advertiser_whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='company_website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
