# Generated by Django 5.2.4 on 2025-08-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0002_alter_billboard_advertiser_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
