# Generated by Django 5.2.4 on 2025-08-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0004_alter_billboard_options_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
