# Generated by Django 5.2.4 on 2025-08-28 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0005_billboard_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='ooh_media_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='billboard',
            index=models.Index(fields=['is_active', 'created_at'], name='billboards__is_acti_95ba1f_idx'),
        ),
        migrations.AddIndex(
            model_name='billboard',
            index=models.Index(fields=['user', 'is_active'], name='billboards__user_id_ef4b19_idx'),
        ),
        migrations.AddIndex(
            model_name='billboard',
            index=models.Index(fields=['city', 'is_active'], name='billboards__city_b3c687_idx'),
        ),
    ]
