# Generated by Django 5.2.4 on 2025-08-31 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0006_alter_billboard_city_alter_billboard_company_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_type', models.CharField(choices=[('phone', 'Phone Call'), ('whatsapp', 'WhatsApp Message'), ('view', 'View')], db_index=True, max_length=20)),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('location', models.JSONField(blank=True, default=dict, help_text='Location data (latitude, longitude)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='billboards.billboard')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['billboard', 'lead_type'], name='billboards__billboa_acf066_idx'), models.Index(fields=['lead_type', 'created_at'], name='billboards__lead_ty_ef5918_idx'), models.Index(fields=['user_ip', 'billboard', 'created_at'], name='billboards__user_ip_7cb936_idx'), models.Index(fields=['user', 'created_at'], name='billboards__user_id_255682_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('lead_type', 'view')), fields=('user_ip', 'billboard', 'lead_type'), name='unique_view_per_ip_per_billboard')],
            },
        ),
    ]
