# Generated by Django 5.2.4 on 2025-08-31 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0007_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='billboard',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='user',
        ),
        migrations.AddField(
            model_name='billboard',
            name='phone_leads',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='billboard',
            name='whatsapp_leads',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='billboard',
            index=models.Index(fields=['phone_leads', 'whatsapp_leads'], name='billboards__phone_l_908d78_idx'),
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
