# Generated by Django 5.2.4 on 2025-09-28 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0007_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='lead',
            name='unique_view_per_ip_per_billboard',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='billboards__billboa_acf066_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='billboards__lead_ty_ef5918_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='billboards__user_ip_7cb936_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='billboards__user_id_255682_idx',
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('billboard', 'user_ip')},
        ),
        migrations.AddField(
            model_name='billboard',
            name='leads',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='lead',
            name='billboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_interactions', to='billboards.billboard'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='billboard',
            index=models.Index(fields=['leads'], name='billboards__leads_c0fc38_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['billboard', 'user_ip'], name='billboards__billboa_603fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['user_ip', 'created_at'], name='billboards__user_ip_5db7d8_idx'),
        ),
        migrations.AddField(
            model_name='view',
            name='billboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_interactions', to='billboards.billboard'),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='location',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='user',
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['billboard', 'user_ip'], name='billboards__billboa_0c783d_idx'),
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['user_ip', 'created_at'], name='billboards__user_ip_5078a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='view',
            unique_together={('billboard', 'user_ip')},
        ),
    ]
