# Generated by Django 5.2.4 on 2025-08-31 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0008_remove_lead_billboard_remove_lead_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='billboard',
            name='billboards__phone_l_908d78_idx',
        ),
        migrations.RenameField(
            model_name='billboard',
            old_name='phone_leads',
            new_name='leads',
        ),
        migrations.RemoveField(
            model_name='billboard',
            name='whatsapp_leads',
        ),
        migrations.AddIndex(
            model_name='billboard',
            index=models.Index(fields=['leads'], name='billboards__leads_c0fc38_idx'),
        ),
    ]
