# Generated by Django 5.2.4 on 2025-09-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0008_view_remove_lead_unique_view_per_ip_per_billboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='address',
            field=models.TextField(blank=True, help_text='Detailed address of the billboard location', null=True),
        ),
        migrations.AddField(
            model_name='billboard',
            name='generator_backup',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Whether the billboard has generator backup', max_length=3, null=True),
        ),
    ]
