# Generated by Django 5.2.4 on 2025-08-31 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0009_remove_billboard_billboards__phone_l_908d78_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('billboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_interactions', to='billboards.billboard')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['billboard', 'user_ip'], name='billboards__billboa_603fdb_idx'), models.Index(fields=['user_ip', 'created_at'], name='billboards__user_ip_5db7d8_idx')],
                'unique_together': {('billboard', 'user_ip')},
            },
        ),
    ]
