# Generated by Django 5.2.4 on 2025-10-26 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0009_billboard_address_billboard_generator_backup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Current approval status of the billboard', max_length=20),
        ),
        migrations.AddField(
            model_name='billboard',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the billboard was approved', null=True),
        ),
        migrations.AddField(
            model_name='billboard',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who approved this billboard', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_billboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billboard',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When the billboard was rejected', null=True),
        ),
        migrations.AddField(
            model_name='billboard',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who rejected this billboard', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_billboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billboard',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if applicable)', null=True),
        ),
        migrations.AddIndex(
            model_name='billboard',
            index=models.Index(fields=['approval_status'], name='billboards__approva_980b63_idx'),
        ),
        migrations.AddIndex(
            model_name='billboard',
            index=models.Index(fields=['approval_status', 'is_active'], name='billboards__approva_568954_idx'),
        ),
        migrations.AddIndex(
            model_name='billboard',
            index=models.Index(fields=['user', 'approval_status'], name='billboards__user_id_724451_idx'),
        ),
    ]
