# Generated by Django 5.2.4 on 2025-11-14 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0010_billboard_approval_status_billboard_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='view',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who clicked lead (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='view',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who viewed (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['billboard', 'user'], name='billboards__billboa_938af2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['billboard', 'user', 'created_at'], name='billboards__billboa_883593_idx'),
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['billboard', 'user'], name='billboards__billboa_b83abd_idx'),
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['billboard', 'user', 'created_at'], name='billboards__billboa_4af2fa_idx'),
        ),
    ]
