# Generated by Django 5.2.4 on 2025-11-22 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0011_alter_lead_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='billboard',
            index=models.Index(fields=['latitude', 'longitude'], name='billboards__latitud_43aaa9_idx'),
        ),
        migrations.AddIndex(
            model_name='billboard',
            index=models.Index(fields=['approval_status', 'is_active', 'latitude', 'longitude'], name='billboards__approva_e14c1a_idx'),
        ),
    ]
