# Generated by Django 5.2.4 on 2026-06-13 21:42

import django.contrib.gis.db.models.fields
from django.db import migrations

from billboards.geo_utils import backfill_billboard_locations


def forwards(apps, schema_editor):
    Billboard = apps.get_model('billboards', 'Billboard')
    backfill_billboard_locations(Billboard)


class Migration(migrations.Migration):

    dependencies = [
        ('billboards', '0013_billboard_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                help_text='PostGIS geography point (synced from latitude/longitude)',
                null=True,
                srid=4326,
            ),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
