# Generated by Django 5.2.4 on 2026-06-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('state', models.CharField(max_length=100, unique=True)),
                ('boundary', models.JSONField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'state boundaries',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('state_abbr', models.CharField(db_index=True, max_length=2)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('coordinates', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('country_id', models.BigIntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=191)),
                ('county_name', models.CharField(blank=True, default='', max_length=191)),
                ('state_name', models.CharField(blank=True, default='', max_length=191)),
                ('zip_codes', models.TextField(blank=True, default='')),
                ('place_type', models.CharField(blank=True, default='', max_length=191)),
                ('latitude', models.CharField(blank=True, default='', max_length=191)),
                ('longitude', models.CharField(blank=True, default='', max_length=191)),
                ('area_code', models.CharField(blank=True, default='', max_length=191)),
                ('population', models.CharField(blank=True, default='', max_length=191)),
                ('households', models.CharField(blank=True, default='', max_length=191)),
                ('median_income', models.CharField(blank=True, default='', max_length=191)),
                ('land_area', models.CharField(blank=True, default='', max_length=191)),
                ('water_area', models.CharField(blank=True, default='', max_length=191)),
                ('time_zone', models.CharField(blank=True, default='', max_length=191)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['state_abbr', 'name'],
                'indexes': [models.Index(fields=['state_abbr', 'name'], name='locations_c_state_a_6fc865_idx'), models.Index(fields=['enabled'], name='locations_c_enabled_3851a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='CityBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('boundary', models.JSONField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'city boundaries',
                'constraints': [models.UniqueConstraint(fields=('city', 'state'), name='uniq_city_boundary_city_state')],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('abbr', models.CharField(db_index=True, max_length=2)),
                ('capital', models.CharField(max_length=50)),
                ('coordinates', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('country_id', models.BigIntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=191)),
                ('region', models.CharField(blank=True, default='', max_length=191)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['abbr'], name='locations_s_abbr_40aaed_idx'), models.Index(fields=['enabled'], name='locations_s_enabled_45fe97_idx')],
            },
        ),
    ]
