# Generated by Django 5.2.4 on 2025-11-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('new_view', 'New View'), ('wishlist_added', 'Added to Wishlist'), ('billboard_activated', 'Billboard Activated'), ('billboard_deactivated', 'Billboard Deactivated'), ('billboard_approved', 'Billboard Approved'), ('billboard_rejected', 'Billboard Rejected'), ('price_update', 'Price Update'), ('system_message', 'System Message'), ('welcome', 'Welcome Message')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('new_view', 'New View'), ('wishlist_added', 'Added to Wishlist'), ('billboard_activated', 'Billboard Activated'), ('billboard_deactivated', 'Billboard Deactivated'), ('billboard_approved', 'Billboard Approved'), ('billboard_rejected', 'Billboard Rejected'), ('price_update', 'Price Update'), ('system_message', 'System Message'), ('welcome', 'Welcome Message')], db_index=True, max_length=50),
        ),
    ]
