# Generated by Django 5.2.4 on 2026-04-12 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0002_alter_notificationtemplate_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('new_view', 'New View'), ('wishlist_added', 'Added to Wishlist'), ('billboard_activated', 'Billboard Activated'), ('billboard_deactivated', 'Billboard Deactivated'), ('billboard_approved', 'Billboard Approved'), ('billboard_rejected', 'Billboard Rejected'), ('price_update', 'Price Update'), ('system_message', 'System Message'), ('welcome', 'Welcome Message')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['is_active', 'notification_type'], name='notificatio_is_acti_5e7c55_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotification',
            index=models.Index(fields=['recipient', 'sent_at'], name='notificatio_recipie_179e69_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotification',
            index=models.Index(fields=['recipient', 'opened'], name='notificatio_recipie_f57218_idx'),
        ),
    ]
